name: Deploy updates

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        run: |
          npm install
          GATSBY_API_URL=//api.fredericpaurisse.fr gatsby build
          sshpass -p ${{secrets.SSH_PASS}} \
          rsync -e "ssh -o StrictHostKeyChecking=no" \
          -av --delete ./public/ ./.cache/ \
          ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/var/www/portfolio/portfolio-gatsby/
