name: Deploy updates

on:
  push:
    branches: master
  #schedule:
   #- cron: "*/5 * * * *"
     
jobs: 
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        run: |
          npm install
          npm run clean
          npm run build
          sshpass -p ${{secrets.SSH_PASS}} \
          rsync -e "ssh -o StrictHostKeyChecking=no" \
          -av --delete ./public/ \
          ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/var/www/portfolio/portfolio-gatsby/
        env:
          GATSBY_API_URL: "https://api.fredericpaurisse.fr/"
