name: Deploy updates

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Deploy
        run: |
          sshpass -p ${{secrets.SSH_PASS}} \
          rsync -e "ssh -o StrictHostKeyChecking=no" \
          ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/var/www/portfolio/portfolio-gatsby/
        
      - name: Install dependencies
        run: npm install
  
      - name: Build
        run: npm run build
        env:
          GATSBY_API_URL: "https://api.fredericpaurisse.fr"